"""empty message

Revision ID: 66920edda65c
Revises: e9aa22e57996
Create Date: 2019-03-31 20:04:51.029087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66920edda65c'
down_revision = 'e9aa22e57996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('action', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scenario', 'request_action', ['action'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenario', type_='foreignkey')
    op.drop_column('scenario', 'action')
    # ### end Alembic commands ###
