"""empty message

Revision ID: 78fb1bf8f690
Revises: bef2a2f5c2d7
Create Date: 2019-03-29 22:34:17.854309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78fb1bf8f690'
down_revision = 'bef2a2f5c2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('description', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'description')
    # ### end Alembic commands ###
