"""empty message

Revision ID: c719635d52cb
Revises: 66920edda65c
Create Date: 2019-03-31 20:32:00.015806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c719635d52cb'
down_revision = '66920edda65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('schedule', sa.Integer(), nullable=True))
    op.drop_constraint('scenario_srchedule_fkey', 'scenario', type_='foreignkey')
    op.create_foreign_key(None, 'scenario', 'schedule', ['schedule'], ['id'])
    op.drop_column('scenario', 'srchedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('srchedule', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scenario', type_='foreignkey')
    op.create_foreign_key('scenario_srchedule_fkey', 'scenario', 'schedule', ['srchedule'], ['id'])
    op.drop_column('scenario', 'schedule')
    # ### end Alembic commands ###
