"""empty message

Revision ID: e9aa22e57996
Revises: 78fb1bf8f690
Create Date: 2019-03-31 11:41:00.068093

"""
from alembic import op
import sqlalchemy as sa

from app.models.action import JSON

# revision identifiers, used by Alembic.
revision = 'e9aa22e57996'
down_revision = '78fb1bf8f690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('schema', sa.String(length=5), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=False),
    sa.Column('headers', JSON(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('scenario', sa.Column('srchedule', sa.Integer(), nullable=True))
    op.drop_constraint('scenario_schedule_fkey', 'scenario', type_='foreignkey')
    op.create_foreign_key(None, 'scenario', 'schedule', ['srchedule'], ['id'])
    op.drop_column('scenario', 'schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('schedule', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scenario', type_='foreignkey')
    op.create_foreign_key('scenario_schedule_fkey', 'scenario', 'schedule', ['schedule'], ['id'])
    op.drop_column('scenario', 'srchedule')
    op.drop_table('request_action')
    # ### end Alembic commands ###
